### ISSUE TITLE
Documentation for development setup

### ISSUE THREAD

**Issue by sagargg** [Aadesh-Baral/OSMLocalizer#123]
As the project grows, it is crucial to provide comprehensive and well-structured documentation to guide new development contributors when they join the project. This issue aims to develop detailed documentation that will serve as a reference for new team members, enabling them to get up to speed and make meaningful contributions quickly.

## Acceptance Criteria
* [ ] There is a getting started guide doc that includes step-by-step instructions for setting up the development environment. It should include the below details. 
    * [ ] Project architecture, explaining the overall structure and how different components interact.
    * [ ] An overview of the coding standards and best practices followed within the project.
    * [ ] Document the tools and libraries used in the project, along with instructions on integrating them.

**Comment by sagargg** [comment]
@Aadesh-Baral  Created an issue here. Please start adding some detail here (in points) and then we can develop proper documentation.

**Comment by Aadesh-Baral** [comment]
Sounds good , @sagargg. I think this can be divided into multiple documents, such as contributor guidelines and development setup.

**Comment by Aadesh-Baral** [comment]
@sagargg Added contributor guidelines and development setup docs. Please let me know if every thing is covered in the docs.
