### ISSUE TITLE
Remove weekday and time info from data sourced field.

### ISSUE THREAD

**Issue by Aadesh-Baral** [Aadesh-Baral/OSMLocalizer#129]
Currently on the frontend Task Data Sourced is displayed in the format -> `Tue, 07 Mar 2023 15:39:07 GMT`. Weekday and time information are not that relevant in this case and takes extra space in challenge detail view. So we can just display the month date and year in this place like `07 Mar 2023`.

**Comment by fiskryeziu** [comment]
May I work on this?

**Comment by Aadesh-Baral** [comment]
Yeah sure @fiskryeziu

**Comment by fiskryeziu** [comment]
Since it's a date you only need to format it like : 
```javascript
const createdDate = new Date(props.challenge.created);
const formattedDate = createdDate.toLocaleDateString('en-US', {
  day: '2-digit',
  month: 'short',
  year: 'numeric'
});

return <div>{formattedDate}</div>;
```

**Comment by Aadesh-Baral** [comment]
@fiskryeziu  Can you create a PR for this?
